export enum ActionType {
    FETCH_JOBS = 'FETCH_JOBS',
    FETCH_SEARCHED_JOBS = 'FETCH_SEARCHED_JOBS',
    FETCH_BY_CATEGORY = 'FETCH_BY_CATEGORY',
    FETCH_COMPANY = 'FETCH_COMPANY',
    ADD_TO_SAVED = 'ADD_TO_SAVED',
    REMOVE_FROM_SAVED = 'REMOVE_FROM_SAVED'
}